"""
Tests for validating Whisper transcription quality metrics.
This module tests the quality metrics generated by the transcription service.
"""
import asyncio
import unittest
from unittest.mock import Mock, patch, AsyncMock
import numpy as np
import tempfile
import os
from datetime import datetime

from ..shared.utils.audio_utils import get_audio_processor
from ..vla.voice_interface.transcription_service import get_default_transcription_service
from ..vla.voice_interface.models import EnhancedVoiceCommand
from ..config.config import get_config


class TestWhisperTranscriptionQuality(unittest.TestCase):
    """
    Test class for validating Whisper transcription quality metrics.
    """
    
    def setUp(self):
        """
        Set up test fixtures before each test method.
        """
        self.config = get_config()
        self.audio_processor = get_audio_processor()
        self.transcription_service = get_default_transcription_service()
        
        # Sample test phrases
        self.test_phrases = [
            "Clean the room",
            "Go to the kitchen and bring me a cup",
            "Move forward two meters",
            "Turn left and stop",
            "Find the red ball"
        ]
    
    def generate_test_audio(self, text: str, noise_level: float = 0.0) -> bytes:
        """
        Generate test audio for a given text phrase with optional noise.
        NOTE: In a real implementation, this would synthesize audio from text.
        For this test, we'll create a placeholder.
        
        Args:
            text: Text to synthesize
            noise_level: Level of background noise (0.0 to 1.0)
            
        Returns:
            Generated audio as bytes
        """
        # Create some dummy audio data
        duration = len(text.split()) * 0.5  # Approximate duration based on text length
        if duration < 1.0:
            duration = 1.0  # Minimum duration of 1 second
        
        sample_rate = self.config.get('VOICE.SAMPLE_RATE')
        samples = int(duration * sample_rate)
        
        # Generate simple audio (for testing purposes)
        t = np.linspace(0, duration, samples)
        # Create a more complex waveform to simulate speech
        audio_signal = np.zeros_like(t)
        for i, char in enumerate(text):
            # Create a simple tone for each character group
            freq = 200 + (ord(char) % 26) * 20  # Frequency based on character
            start_idx = int((i / len(text)) * samples)
            end_idx = int(((i + 1) / len(text)) * samples)
            if end_idx > start_idx:
                segment_t = t[start_idx:end_idx]
                audio_signal[start_idx:end_idx] += 0.3 * np.sin(2 * np.pi * freq * segment_t)
        
        # Add noise if requested
        if noise_level > 0:
            noise = np.random.normal(0, noise_level, samples)
            audio_signal = audio_signal + noise
        
        # Normalize
        audio_signal = audio_signal / np.max(np.abs(audio_signal)) if np.max(np.abs(audio_signal)) != 0 else audio_signal
        
        # Convert to bytes
        audio_bytes = (audio_signal * 32767).astype(np.int16).tobytes()
        
        return audio_bytes
    
    def test_confidence_score_range(self):
        """
        Test that confidence scores are within the expected range (0-1).
        """
        print("\nTesting confidence score range...")
        
        for test_phrase in self.test_phrases:
            with self.subTest(phrase=test_phrase):
                # Generate clean audio for the test phrase
                audio_data = self.generate_test_audio(test_phrase, noise_level=0.05)
                
                # Transcribe the audio
                result = asyncio.run(
                    self.transcription_service.transcribe_audio_bytes(audio_data)
                )
                
                if result.success and result.voice_command:
                    confidence = result.voice_command.confidence
                    
                    print(f"Phrase: '{test_phrase}', Confidence: {confidence}")
                    
                    # Check that confidence is within 0-1 range
                    self.assertGreaterEqual(confidence, 0.0, f"Confidence {confidence} is below 0")
                    self.assertLessEqual(confidence, 1.0, f"Confidence {confidence} is above 1")
                else:
                    print(f"Failed to transcribe: {test_phrase}")
                    # Even if transcription fails, the test should pass if the system handles it gracefully
                    self.assertIsNotNone(result.error_message)
    
    def test_average_confidence_calculation(self):
        """
        Test the calculation of average confidence across segments.
        """
        print("\nTesting average confidence calculation...")
        
        # Create a voice command with segments
        voice_command = EnhancedVoiceCommand(
            id="test-123",
            timestamp=datetime.now(),
            transcription="Test command",
            confidence=0.8,
            intent="test"
        )
        
        # Add some segments with different confidences
        voice_command.add_segment(0.0, 1.0, "Test", 0.9)
        voice_command.add_segment(1.0, 2.0, "command", 0.7)
        voice_command.add_segment(2.0, 3.0, "processing", 0.85)
        
        # Calculate average confidence
        avg_confidence = voice_command.calculate_average_confidence()
        
        print(f"Average confidence: {avg_confidence}")
        
        # Expected average: (0.9 + 0.7 + 0.85) / 3 = 0.8167
        expected_avg = (0.9 + 0.7 + 0.85) / 3
        self.assertAlmostEqual(avg_confidence, expected_avg, places=3)
    
    def test_audio_quality_score_inclusion(self):
        """
        Test that audio quality scores are included in voice commands.
        """
        print("\nTesting audio quality score inclusion...")
        
        for test_phrase in self.test_phrases:
            with self.subTest(phrase=test_phrase):
                # Generate audio with different noise levels
                audio_data = self.generate_test_audio(test_phrase, noise_level=0.1)
                
                # Transcribe the audio
                result = asyncio.run(
                    self.transcription_service.transcribe_audio_bytes(audio_data)
                )
                
                if result.success and result.voice_command:
                    voice_command = result.voice_command
                    
                    print(f"Phrase: '{test_phrase}', Quality Score: {voice_command.audio_quality_score}")
                    
                    # Check that the quality score is included
                    self.assertIsNotNone(voice_command.audio_quality_score)
                    self.assertIsInstance(voice_command.audio_quality_score, float)
                    
                    # Quality score should be between 0 and 1
                    self.assertGreaterEqual(voice_command.audio_quality_score, 0.0)
                    self.assertLessEqual(voice_command.audio_quality_score, 1.0)
                else:
                    print(f"Failed to transcribe: {test_phrase}")
    
    def test_processing_time_inclusion(self):
        """
        Test that processing times are included in voice commands.
        """
        print("\nTesting processing time inclusion...")
        
        for test_phrase in self.test_phrases:
            with self.subTest(phrase=test_phrase):
                # Generate audio for the test phrase
                audio_data = self.generate_test_audio(test_phrase, noise_level=0.05)
                
                # Transcribe the audio
                result = asyncio.run(
                    self.transcription_service.transcribe_audio_bytes(audio_data)
                )
                
                if result.success and result.voice_command:
                    voice_command = result.voice_command
                    
                    print(f"Phrase: '{test_phrase}', Processing Time: {voice_command.processing_time_ms} ms")
                    
                    # Check that processing time is included
                    self.assertIsNotNone(voice_command.processing_time_ms)
                    self.assertIsInstance(voice_command.processing_time_ms, (float, int))
                    
                    # Processing time should be positive
                    self.assertGreaterEqual(voice_command.processing_time_ms, 0.0)
                else:
                    print(f"Failed to transcribe: {test_phrase}")
    
    def test_voice_activity_detection_inclusion(self):
        """
        Test that voice activity information is included in voice commands.
        """
        print("\nTesting voice activity detection inclusion...")
        
        for test_phrase in self.test_phrases:
            with self.subTest(phrase=test_phrase):
                # Generate audio for the test phrase
                audio_data = self.generate_test_audio(test_phrase, noise_level=0.05)
                
                # Transcribe the audio
                result = asyncio.run(
                    self.transcription_service.transcribe_audio_bytes(audio_data)
                )
                
                if result.success and result.voice_command:
                    voice_command = result.voice_command
                    
                    print(f"Phrase: '{test_phrase}', Voice Activity: {voice_command.voice_activity}")
                    
                    # Check that voice activity information is included
                    self.assertIsNotNone(voice_command.voice_activity)
                    
                    # If voice activity is detected, it should have meaningful values
                    if voice_command.voice_activity.has_voice:
                        self.assertIsNotNone(voice_command.voice_activity.voice_start_time)
                        self.assertIsNotNone(voice_command.voice_activity.voice_end_time)
                        self.assertGreaterEqual(voice_command.voice_activity.total_voice_duration, 0.0)
                else:
                    print(f"Failed to transcribe: {test_phrase}")
    
    def test_quality_metrics_under_different_conditions(self):
        """
        Test quality metrics under different acoustic conditions.
        """
        print("\nTesting quality metrics under different conditions...")
        
        test_conditions = [
            ("Low noise", 0.05),
            ("Medium noise", 0.2),
            ("High noise", 0.5)
        ]
        
        for condition_name, noise_level in test_conditions:
            print(f"\nTesting with {condition_name} ({noise_level} noise)...")
            
            # Use a simple, clear phrase
            test_phrase = "Clean the room"
            audio_data = self.generate_test_audio(test_phrase, noise_level=noise_level)
            
            # Transcribe the audio
            result = asyncio.run(
                self.transcription_service.transcribe_audio_bytes(audio_data)
            )
            
            if result.success and result.voice_command:
                voice_command = result.voice_command
                
                print(f"  Transcription: '{voice_command.transcription}'")
                print(f"  Confidence: {voice_command.confidence:.3f}")
                print(f"  Quality Score: {voice_command.audio_quality_score:.3f}")
                print(f"  Processing Time: {voice_command.processing_time_ms:.2f} ms")
                
                # Check that all required metrics are present
                self.assertIsNotNone(voice_command.confidence)
                self.assertIsNotNone(voice_command.audio_quality_score)
                self.assertIsNotNone(voice_command.processing_time_ms)
                self.assertIsNotNone(voice_command.voice_activity)
                
                # As noise increases, we expect confidence to potentially decrease
                # (though this is not guaranteed with our simple test audio)
            else:
                print(f"  Failed to transcribe with {condition_name} condition")
    
    def test_result_success_metrics(self):
        """
        Test metrics associated with successful transcription results.
        """
        print("\nTesting metrics for successful transcription results...")
        
        # Use a clear, simple phrase
        test_phrase = "Move forward"
        audio_data = self.generate_test_audio(test_phrase, noise_level=0.01)
        
        # Transcribe the audio
        result = asyncio.run(
            self.transcription_service.transcribe_audio_bytes(audio_data)
        )
        
        print(f"Result success: {result.success}")
        print(f"Processing time: {result.processing_time_ms} ms")
        print(f"Confidence score: {result.confidence_score}")
        
        # Check that the result has the expected metrics
        self.assertIsNotNone(result.success)
        self.assertIsNotNone(result.processing_time_ms)
        self.assertIsNotNone(result.confidence_score)
        
        # For a successful result, processing time and confidence should be reasonable
        if result.success:
            self.assertGreater(result.processing_time_ms, 0)
            self.assertGreaterEqual(result.confidence_score, 0)
            self.assertLessEqual(result.confidence_score, 1)


async def run_quality_validation_tests():
    """
    Run comprehensive quality validation tests.
    """
    print("Running comprehensive Whisper transcription quality validation tests...")
    
    # Create a test suite
    suite = unittest.TestLoader().loadTestsFromTestCase(TestWhisperTranscriptionQuality)
    
    # Run the tests
    runner = unittest.TextTestRunner(verbosity=2)
    result = runner.run(suite)
    
    # Return test results
    return result


def test_transcription_quality_metrics():
    """
    Test validation of Whisper transcription quality metrics.
    """
    print("Testing validation of Whisper transcription quality metrics...")
    
    # Run the tests
    result = asyncio.run(run_quality_validation_tests())
    
    # Print a summary
    print(f"\nTest Results Summary:")
    print(f"Tests run: {result.testsRun}")
    print(f"Failures: {len(result.failures)}")
    print(f"Errors: {len(result.errors)}")
    
    if result.failures:
        print("\nFailures:")
        for failure in result.failures:
            print(failure[1])
    
    if result.errors:
        print("\nErrors:")
        for error in result.errors:
            print(error[1])
    
    return result.wasSuccessful()


if __name__ == "__main__":
    success = test_transcription_quality_metrics()
    exit(0 if success else 1)