"""
Base data models for the VLA system based on the specification in data-model.md
"""
from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional, Union, Any
from pydantic import BaseModel, Field


class Point3D(BaseModel):
    """3D point with x, y, z coordinates."""
    x: float
    y: float
    z: float


class Quaternion(BaseModel):
    """Quaternion representation for orientation (x, y, z, w)."""
    x: float
    y: float
    z: float
    w: float


class Pose(BaseModel):
    """Position and orientation in 3D space."""
    position: Point3D
    orientation: Quaternion


class SensorType(str, Enum):
    """Types of sensors available on the robot."""
    CAMERA_RGB = "CAMERA_RGB"
    CAMERA_DEPTH = "CAMERA_DEPTH"
    LIDAR = "LIDAR"
    IMU = "IMU"
    FORCE_TORQUE = "FORCE_TORQUE"


class SensorData(BaseModel):
    """Current readings from a sensor."""
    sensorId: str
    type: SensorType
    data: Any  # Sensor-specific data format
    timestamp: datetime


class JointState(BaseModel):
    """Current state of a robot joint."""
    name: str
    position: float  # Joint angle in radians
    velocity: float  # Joint velocity in rad/s
    effort: float    # Applied torque/force


class RobotCapabilityType(str, Enum):
    """Types of capabilities available on the robot."""
    NAVIGATION = "NAVIGATION"
    MANIPULATION = "MANIPULATION"
    PERCEPTION = "PERCEPTION"
    COMMUNICATION = "COMMUNICATION"


class RobotCapability(BaseModel):
    """A specific capability of the robot."""
    type: RobotCapabilityType
    name: str
    description: str
    enabled: bool


class GripperState(BaseModel):
    """State of a robot gripper."""
    position: float  # Position in meters (0=closed, 1=open)
    force: float     # Applied force in Newtons
    objectHeld: bool
    objectId: Optional[str] = None  # ID of held object if any


class RobotState(BaseModel):
    """Current configuration of the robot."""
    id: str
    timestamp: datetime
    pose: Pose
    jointStates: List[JointState]
    batteryLevel: float  # Battery charge percentage (0-100)
    operationalStatus: str  # ACTIVE, STANDBY, ERROR, CHARGING, MAINTENANCE
    activeTasks: List[str]  # IDs of currently executing tasks
    sensors: List[SensorData]
    gripperState: GripperState
    connected: bool  # Whether robot is connected to system
    capabilities: List[RobotCapability]


class ActionStepType(str, Enum):
    """Types of action steps."""
    NAVIGATION = "NAVIGATION"
    PERCEPTION = "PERCEPTION"
    MANIPULATION = "MANIPULATION"
    WAIT = "WAIT"
    CONDITIONAL = "CONDITIONAL"


class ActionStep(BaseModel):
    """A single action step in an action plan."""
    id: str
    type: ActionStepType
    description: str  # Human-readable description of the action
    parameters: Dict[str, Any]  # Action-specific parameters (e.g. target pose, object ID)
    timeout: int  # Max time to complete this step in seconds
    precondition: Optional[str] = None  # Condition that must be met before this step
    fallbackAction: Optional['ActionStep'] = None  # What to do if this step fails
    estimatedDuration: int  # Estimated duration in seconds


class PlanConstraintType(str, Enum):
    """Types of plan constraints."""
    KINEMATIC = "KINEMATIC"
    SAFETY = "SAFETY"
    ENVIRONMENTAL = "ENVIRONMENTAL"
    RESOURCE = "RESOURCE"


class PlanConstraint(BaseModel):
    """Constraint that applies to an action plan."""
    type: PlanConstraintType
    description: str
    severity: str  # WARNING or ERROR


class ActionPlan(BaseModel):
    """Sequence of ROS 2 actions generated by the LLM to fulfill a command."""
    id: str
    commandId: str  # Reference to originating VoiceCommand
    createdAt: datetime
    actionSequence: List[ActionStep]
    status: str  # PLANNED, IN_PROGRESS, COMPLETED, FAILED, CANCELLED
    estimatedDuration: int  # Estimated time to complete in seconds
    priority: int  # Priority level (0-10)
    constraints: List[PlanConstraint]  # Kinematic, safety, or environmental constraints
    metadata: Dict[str, Any]  # Additional metadata


class VoiceCommand(BaseModel):
    """Represents a spoken instruction from a human user."""
    id: str
    timestamp: datetime
    audioData: Optional[str] = None  # Base64 encoded audio data (optional, may be deleted after processing)
    transcription: str  # Transcribed text from audio
    confidence: float  # Confidence score of transcription (0-1)
    intent: str  # Parsed semantic intent (e.g. "NAVIGATE_TO_LOCATION", "GRASP_OBJECT")
    rawAudioPath: Optional[str] = None  # File path to audio recording (for debugging)
    metadata: Dict[str, str] = Field(default_factory=dict)  # Additional metadata


class OccupancyGrid(BaseModel):
    """Occupancy grid representation of environment."""
    width: int  # Width in cells
    height: int  # Height in cells
    data: List[int]  # Array of values (-1: unknown, 0: free, 100: occupied)


class NavigationCostMap(BaseModel):
    """Cost map for navigation planning."""
    width: int
    height: int
    data: List[int]  # Cost values (higher means more costly to traverse)


class EnvironmentalMap(BaseModel):
    """Representation of the environment including obstacles and objects."""
    id: str
    version: str  # Map version identifier
    createdAt: datetime
    origin: Pose  # Origin of map coordinate frame
    resolution: float  # Resolution of occupancy grid in meters per cell
    occupancyGrid: OccupancyGrid  # Static map data
    dynamicObjects: List['DetectedObject']  # Moving objects detected since map creation
    navigationCosts: NavigationCostMap  # Costs for path planning
    metadata: Dict[str, Union[str, float]]  # Additional metadata


class BoundingBox3D(BaseModel):
    """3D bounding box representation."""
    center: Point3D
    dimensions: Point3D
    corners: List[Point3D]  # 8 corner points


class ObjectAffordanceType(str, Enum):
    """Types of object affordances."""
    GRASP = "grasp"
    PUSH = "push"
    LIFT = "lift"
    MOVE = "move"
    POUR = "pour"


class ObjectAffordance(BaseModel):
    """Possible interaction with an object."""
    type: ObjectAffordanceType
    position: Point3D  # Position where action applies
    direction: Optional[Point3D] = None  # Direction of action (if applicable)
    forceRange: Optional[Dict[str, float]] = None  # Force limits
    metadata: Dict[str, Union[str, float]]  # Additional metadata


class RGBColor(BaseModel):
    """RGB color representation."""
    r: int  # Red value (0-255)
    g: int  # Green value (0-255)
    b: int  # Blue value (0-255)


class GraspType(str, Enum):
    """Types of grasps."""
    POWER = "power"
    PRECISION = "precision"
    PINCH = "pinch"


class GraspPoint(BaseModel):
    """Valid point for grasping an object."""
    position: Point3D  # Position of grasp point
    orientation: Quaternion  # Preferred orientation of gripper
    stabilityScore: float  # How stable this grasp is expected to be (0-1)
    graspType: GraspType  # Type of grasp


class DetectedObject(BaseModel):
    """Identified item in the environment."""
    id: str
    classLabel: str  # Semantic class (e.g. "chair", "cup", "person")
    confidence: float  # Detection confidence (0-1)
    boundingBox: BoundingBox3D  # 3D bounding box
    center: Point3D  # Center position in world coordinates
    dimensions: Point3D  # Size in x, y, z dimensions
    pose: Pose  # Orientation as well as position
    affordances: List[ObjectAffordance]  # Possible interactions
    color: RGBColor  # Dominant color
    material: str  # Material type (e.g. "metal", "plastic", "fabric")
    isGraspable: bool  # Whether object can be grasped
    graspPoints: List[GraspPoint]  # Valid points for grasping
    isMoveable: bool  # Whether object can be moved by robot
    weightEstimate: float  # Estimated weight in kg
    timestamp: datetime  # When object was detected
    sourceSensor: str  # Sensor that detected the object
    trackingId: Optional[str] = None  # ID for tracking across frames


class ExecutionContextStatus(str, Enum):
    """Status of an execution context."""
    INITIALIZING = "INITIALIZING"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    FAILED = "FAILED"
    COMPLETED = "COMPLETED"


class FailedStep(BaseModel):
    """Record of a failed step during execution."""
    stepId: str
    reason: str  # Description of why step failed
    recoveryAttempted: str  # Action taken to recover
    timestamp: datetime


class AdaptationEventType(str, Enum):
    """Types of adaptations during execution."""
    STEP_SKIP = "STEP_SKIP"
    STEP_REPEAT = "STEP_REPEAT"
    STEP_MODIFY = "STEP_MODIFY"
    SUBGOAL_ADD = "SUBGOAL_ADD"


class AdaptationEvent(BaseModel):
    """Record of an adaptation made to a plan during execution."""
    type: AdaptationEventType
    originalStepId: str
    modifiedStep: Optional[ActionStep] = None  # New version of step (for STEP_MODIFY)
    reason: str  # Why adaptation was needed
    timestamp: datetime


class SafetyViolationSeverity(str, Enum):
    """Severity levels for safety violations."""
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


class SafetyViolation(BaseModel):
    """Record of a safety violation encountered during execution."""
    severity: SafetyViolationSeverity
    description: str
    actionTaken: str  # What the system did in response
    timestamp: datetime


class ReplanRequestReason(str, Enum):
    """Reasons for requesting plan replanning."""
    OBSTACLE_DETECTED = "OBSTACLE_DETECTED"
    TARGET_MOVED = "TARGET_MOVED"
    GRASP_FAILED = "GRASP_FAILED"
    PATH_BLOCKED = "PATH_BLOCKED"


class ReplanRequest(BaseModel):
    """Request for plan modification during execution."""
    reason: ReplanRequestReason
    suggestedModification: str  # Description of needed change
    priority: str  # LOW, MEDIUM, HIGH
    timestamp: datetime


class ExecutionContext(BaseModel):
    """Contextual information during task execution."""
    id: str
    planId: str  # Reference to the executing ActionPlan
    startTime: datetime
    currentStepIndex: int  # Index of currently executing step
    completedSteps: List[int]  # Indices of completed steps
    failedSteps: List[FailedStep]  # Steps that failed during execution
    intermediateResults: Dict[str, Any]  # Results from executed steps
    adaptationHistory: List[AdaptationEvent]  # Changes made to plan during execution
    currentStatus: ExecutionContextStatus
    progress: float  # Progress percentage (0-100)
    estimatedTimeRemaining: int  # Estimated seconds until completion
    safetyViolations: List[SafetyViolation]  # Safety issues encountered
    replanRequests: List[ReplanRequest]  # Requests for plan modifications